### ISSUE TITLE
Error when running examples

### ISSUE THREAD

**Issue by mtvu** [twopirllc/AlphaVantageAPI#2]
![image](https://user-images.githubusercontent.com/4926855/97885543-9bfa7f00-1d7b-11eb-99b8-718b217d9436.png)

`ValueError                                Traceback (most recent call last)
<ipython-input-1-3776394bc08b> in <module>
     16 base_fx, to_fx = "USD", "CAD"
     17 
---> 18 found_symbols = df.av.search(query)
     19 
     20 # Global Quote

~/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/alphaVantageAPI/_extension.py in search(self, keywords, **kwargs)
     63     # Search
     64     def search(self, keywords:str, **kwargs) -> pd.DataFrame:
---> 65         self._df = _AV_.search(keywords, **kwargs)
     66         return self._df
     67 

~/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/alphaVantageAPI/alphavantage.py in search(self, keywords, **kwargs)
    400         parameters = {'function': 'SYMBOL_SEARCH', 'keywords': keywords}
    401 
--> 402         download = self._av_api_call(parameters, **kwargs)
    403         return download if download is not None else None
    404 

~/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/alphaVantageAPI/alphavantage.py in _av_api_call(self, parameters, timeout, **kwargs)
    193         # self._response_history.append({'last': time.localtime(), 'parameters': parameters})
    194         if self.datatype == 'json':
--> 195             response = self._to_dataframe(parameters['function'], response)
    196 
    197         if self._api_call_count < 1:

~/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/alphaVantageAPI/alphavantage.py in _to_dataframe(self, function, response)
    266             if len(response[key]) < 1:
    267                 return None
--> 268             df = DataFrame(response[key])
    269         elif function == 'SECTOR':
    270             df = DataFrame.from_dict(response)

~/.pyenv/versions/miniconda3-latest/lib/python3.8/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    527         else:
    528             if index is None or columns is None:
--> 529                 raise ValueError("DataFrame constructor not properly called!")
    530 
    531             if not dtype:

ValueError: DataFrame constructor not properly called!
[1]

`

**Comment by mtvu** [comment]
I ran the example again and got a different error message 
![image](https://user-images.githubusercontent.com/4926855/97890105-40cb8b00-1d81-11eb-8d49-a8e49073263a.png)

**Comment by twopirllc** [comment]
@mtvu,

Doh! Sorry I missed this Issue. I will look into it. Thanks for bringing it to my attention.

KJ

**Comment by mtvu** [comment]
Hi Kevin, 
I ran the classic example and got the error. There is an issue with downloading multiple tickers. And this affects watchlist.py since it uses AlphaVantageAPI under the hood.

**Comment by twopirllc** [comment]
Hello @mtvu,

It looks like you are using the pip version as SECTOR has been removed from the current code on Github. When you get a chance, try uninstalling and then run:
```
$ git clone https://github.com/twopirllc/AlphaVantageAPI.git
```

Thanks
KJ
